substitutions:
  _ORG_ID: '799174817843'
  _FOLDER_NAME: 'Soccer'

steps:
  # Create a folder under the specified organization
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e  # Exit immediately if a command fails
        echo "Attempting to create the ${_FOLDER_NAME} folder under organization ${_ORG_ID}..."
        gcloud resource-manager folders create \
          --display-name="${_FOLDER_NAME}" \
          --organization=${_ORG_ID} || {
            echo "Error: Failed to create folder"
            echo "Checking organization information for debugging:"
            gcloud organizations describe ${_ORG_ID}
            exit 1
          }

options:
  logging: CLOUD_LOGGING_ONLY
