steps:
  # Create the "Soccer" folder with error logging
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e  # Exit immediately if a command fails
        echo "Attempting to create the Soccer folder..."
        gcloud resource-manager folders create \
          --display-name="Soccer" \
          --parent="projects/spry-firefly-446313-u6" || {
            echo "Error: Failed to create folder"
            echo "Checking project information for debugging:"
            gcloud projects describe spry-firefly-446313-u6
            exit 1
          }

options:
  logging: CLOUD_LOGGING_ONLY