steps:
  # Create the "Soccer" folder
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud resource-manager folders create \
          --display-name="Soccer" \
          --parent="projects/spry-firefly-446313-u6"

options:
  logging: CLOUD_LOGGING_ONLY
