substitutions:
  _ORG_ID: '799174817843'    # Organization ID
  _FOLDER_NAME: 'soccer'     # Parent folder name
  _ENVIRONMENT: 'dev'        # Environment delivered from the trigger

steps:
  # Step 1: Check if the folder exists, retrieve its ID, or create the folder if not found
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e  # Exit immediately if a command fails
        echo "Checking if folder ${_FOLDER_NAME} exists under organization ${_ORG_ID}..."
        gcloud resource-manager folders list \
          --organization="${_ORG_ID}" \
          --filter="displayName=${_FOLDER_NAME}" \
          --format="value(name.basename())" > /workspace/folder_id.txt

        if [ ! -s /workspace/folder_id.txt ]; then
          echo "Folder ${_FOLDER_NAME} not found. Creating folder..."
          gcloud resource-manager folders create \
            --display-name="${_FOLDER_NAME}" \
            --organization="${_ORG_ID}" \
            --format="value(name.basename())" > /workspace/folder_id.txt

          echo "Folder created. ID stored in /workspace/folder_id.txt: $(cat /workspace/folder_id.txt)"
        else
          echo "Folder exists. ID stored in /workspace/folder_id.txt: $(cat /workspace/folder_id.txt)"
        fi

  # Step 2: Construct a unique project name using _FOLDER_NAME and _ENVIRONMENT, save it to a file
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e  # Exit immediately if a command fails
        echo "Constructing a unique project name..."
        echo "${_FOLDER_NAME}-${_ENVIRONMENT}-$(date +%s)" > /workspace/project_name.txt
        echo "Project name stored: $(cat /workspace/project_name.txt)"

  # Step 3: Read folder ID and project name from files and create the project
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e  # Exit immediately if a command fails
        if [ ! -f /workspace/folder_id.txt ]; then
          echo "Error: Folder ID file not found."
          exit 1
        fi

        if [ ! -f /workspace/project_name.txt ]; then
          echo "Error: Project name file not found."
          exit 1
        fi

        echo "Reading folder ID and project name..."
        echo "Folder ID: $(cat /workspace/folder_id.txt)"
        echo "Project Name: $(cat /workspace/project_name.txt)"
        echo "Attempting to create the project..."

        gcloud projects create "$(cat /workspace/project_name.txt)" \
          --folder="$(cat /workspace/folder_id.txt)" || {
            echo "Error: Failed to create project"
            exit 1
          }

        echo "Project successfully created."

  # Step 4: Deploy the service-check Cloud Function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e  # Exit immediately if a command fails
        if [ ! -f /workspace/project_name.txt ]; then
          echo "Error: Project name file not found."
          exit 1
        fi

        echo "Deploying Cloud Function to project: $(cat /workspace/project_name.txt)..."

        # Set the active project
        gcloud config set project "$(cat /workspace/project_name.txt)"

        # Deploy the Cloud Function
        gcloud functions deploy service-check \
            --entry-point=app \
            --runtime=python39 \
            --trigger-http \
            --allow-unauthenticated \
            --region=us-central1 \
            --source=gcp/cloud-functions/service-check

        echo "Cloud Function 'service-check' deployed successfully."

options:
  logging: CLOUD_LOGGING_ONLY
