steps:
  # Trigger: 010-check-or-create-folder
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: '010-check-or-create-folder'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        gcloud beta builds triggers run 83bf9b23-f39e-4c32-82f2-15da23226de5 \
          --project=org-service-account-001 || {
          echo "Error: Trigger failed for check-or-create-folder."
          exit 1
        }

  # Trigger: 020-check-or-create-project
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: '020-check-or-create-project'
    waitFor: ['010-check-or-create-folder']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        gcloud beta builds triggers run 15257bc8-581a-47f9-b3a5-08f35742553e \
          --project=org-service-account-001 \
          --substitutions=_ENVIRONMENT=${_ENVIRONMENT} || {
          echo "Error: Trigger failed for check-or-create-project."
          exit 1
        }

  # Trigger: 030-enable-billing
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: '030-enable-billing'
    waitFor: ['020-check-or-create-project']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        gcloud beta builds triggers run 782d9876-eb96-4581-bfee-85b1c825fd75 \
          --project=org-service-account-001 \
          --substitutions=_ENVIRONMENT=${_ENVIRONMENT} || {
          echo "Error: Trigger failed for enable-billing."
          exit 1
        }

  # Trigger: 040-enable-cloud-functions
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: '040-enable-cloud-functions'
    waitFor: ['030-enable-billing']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        gcloud beta builds triggers run 93cd455e-fcf8-4b50-9781-32bf6037ba89 \
          --project=org-service-account-001 \
          --substitutions=_ENVIRONMENT=${_ENVIRONMENT} || {
          echo "Error: Trigger failed for enable-cloud-functions."
          exit 1
        }

  # Trigger: 050-add-cloudbuild-iam-policy
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: '050-add-cloudbuild-iam-policy'
    waitFor: ['040-enable-cloud-functions']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        gcloud beta builds triggers run a8da0b8c-01d5-4c27-958b-7eab3b7ed00f \
          --project=org-service-account-001 \
          --substitutions=_ENVIRONMENT=${_ENVIRONMENT} || {
          echo "Error: Trigger failed for add-cloudbuild-iam-policy."
          exit 1
        }

  # Trigger: 060-deploy-cloud-function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: '060-deploy-cloud-function'
    waitFor: ['050-add-cloudbuild-iam-policy']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        gcloud beta builds triggers run f6de475f-0bd6-48b0-ae13-687a5f84a03f \
          --project=org-service-account-001 \
          --substitutions=_ENVIRONMENT=${_ENVIRONMENT} || {
          echo "Error: Trigger failed for deploy-cloud-function."
          exit 1
        }

  # Trigger: 070-test-service-check
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: '070-test-service-check'
    waitFor: ['060-deploy-cloud-function']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        gcloud beta builds triggers run af1d2829-bf23-4125-aa52-373e47001e4a \
          --project=org-service-account-001 \
          --substitutions=_ENVIRONMENT=${_ENVIRONMENT} || {
          echo "Error: Trigger failed for test-service-check."
          exit 1
        }

timeout: '3600s' # Timeout for the entire build
options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE
