steps:
  # Step 1: Retrieve the Folder ID for "Soccer" and write it to a file in /workspace
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Retrieving the Folder ID for 'Soccer'..."
        gcloud resource-manager folders list \
          --filter="displayName=Soccer" \
          --format="value(ID)" > /workspace/folder_id.txt
        if [ ! -s /workspace/folder_id.txt ]; then
          echo "Error: Folder 'Soccer' not found. Exiting."
          exit 1
        else
          echo "Folder ID for 'Soccer' written to /workspace/folder_id.txt."
        fi

  # Step 2: Delete the "Soccer" folder using the Folder ID from the file
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deleting the 'Soccer' folder..."
        gcloud resource-manager folders delete $(cat /workspace/folder_id.txt) --quiet
        echo "Successfully deleted the 'Soccer' folder."

options:
  logging: CLOUD_LOGGING_ONLY

substitutions: {}
