steps:
  # Authenticate with gcloud
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args:
      - 'auth'
      - 'activate-service-account'
      - '--key-file=/workspace/sa-key.json'

  # Create the "Soccer" folder
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud resource-manager folders create \
          --display-name="Soccer" \
          --parent="projects/spry-firefly-446313-u6"

availableSecrets:
  secretManager:
    - versionName: "projects/spry-firefly-446313-u6/secrets/sa-key/versions/latest"
      env: "SA_KEY_JSON"
