steps:
  # Create the "Soccer" folder under the organization
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e  # Exit immediately if a command fails
        echo "Attempting to create the Soccer folder under organization 799174817843..."
        gcloud resource-manager folders create \
          --display-name="Soccer" \
          --organization=799174817843 || {
            echo "Error: Failed to create folder"
            echo "Checking organization information for debugging:"
            gcloud organizations describe 799174817843
            exit 1
          }

options:
  logging: CLOUD_LOGGING_ONLY
