substitutions:
  _ENVIRONMENT: 'dev'
  _FOLDER_NAME: 'soccer'

steps:
  # Step 1: Get the project ID
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'get-project-id'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        gcloud projects list \
          --filter="name~^${_FOLDER_NAME}-${_ENVIRONMENT}" \
          --format="value(projectId)" \
          | head -n 1 > /workspace/FIREBASE_PROJECT_ID.txt

  # Step 2: Install Firebase CLI
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'install-firebase-cli'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        curl -sL https://firebase.tools | bash
        mkdir -p /workspace/firebase
        cp /usr/local/bin/firebase /workspace/firebase/
        chmod +x /workspace/firebase/firebase

  # Step 3: Deploy scheduled function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'deploy-function'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        project_id=$(cat /workspace/FIREBASE_PROJECT_ID.txt)
        echo "🚀 Deploying scheduled function to delete unverified users..."
        cd firebase/functions/delete-unverified-users
        /workspace/firebase/firebase deploy --only functions:deleteUnverifiedUsers --project="$project_id" --force

options:
  logging: CLOUD_LOGGING_ONLY
