# deploy_realtime_db_locked.yaml
substitutions:
  _ENVIRONMENT: 'dev'
  _FOLDER_NAME: 'soccer'

steps:
# 0. Resolve Firebase project ID
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: 'get-project-id'
  entrypoint: bash
  args:
    - '-c'
    - |
      set -e
      gcloud projects list \
        --filter="name~^${_FOLDER_NAME}-${_ENVIRONMENT}" \
        --format="value(projectId)" \
        | head -n1 > /workspace/FIREBASE_PROJECT_ID.txt
      test -s /workspace/FIREBASE_PROJECT_ID.txt

# 1. Install Firebase CLI (fixed)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: 'install-firebase-cli'
  entrypoint: bash
  args:
    - '-c'
    - |
      set -e
      echo "⬇️ Installing Firebase CLI..."
      curl -sL https://firebase.tools | bash
      mkdir -p /workspace/firebase
      cp /usr/local/bin/firebase /workspace/firebase/
      chmod +x /workspace/firebase/firebase
      echo "✅ Firebase CLI installed."

# 2. Create the default RTDB instance in us-central1
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: 'create-default-rtdb'
  entrypoint: bash
  args:
    - '-c'
    - |
      set -e
      project_id=$(cat /workspace/FIREBASE_PROJECT_ID.txt)
      instance="${project_id}-default-rtdb"
      echo "🚀 Creating default RTDB $instance in us-central1…"
      /workspace/firebase/firebase database:instances:create "$instance" \
        --location us-central1 \
        --project "$project_id" \
      || echo "ℹ️ Instance already exists."

# 3. Deploy *locked-mode* rules from the external file
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: 'deploy-locked-rules'
  entrypoint: bash
  args:
    - '-c'
    - |
      set -e
      project_id=$(cat /workspace/FIREBASE_PROJECT_ID.txt)
      cd /workspace   # firebase.json & database.rules.json must be here
      echo "🔒 Deploying locked-mode rules…"
      /workspace/firebase/firebase deploy \
        --only database \
        --project "$project_id" \
        --force

options:
  logging: CLOUD_LOGGING_ONLY
