substitutions:
  _ENVIRONMENT: 'dev'
  _FOLDER_NAME: 'soccer'

steps:
  # Step 1: Retrieve the project ID
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "Checking if project starting with ${_FOLDER_NAME}-${_ENVIRONMENT} exists..."
        gcloud projects list \
          --filter="name~^${_FOLDER_NAME}-${_ENVIRONMENT}" \
          --format="value(projectId)" | head -n 1 > /workspace/SOCCER_PROJECT_ID.txt

        if [ ! -s /workspace/SOCCER_PROJECT_ID.txt ] || [ -z "$(cat /workspace/SOCCER_PROJECT_ID.txt)" ]; then
          echo "❌ Error: Project ID not found. Ensure the project exists."
          exit 1
        fi
        echo "✅ Using project: $(cat /workspace/SOCCER_PROJECT_ID.txt)"

  # Step 2: Enable Firebase in the project
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "🔓 Enabling Firebase in project $(cat /workspace/SOCCER_PROJECT_ID.txt)..."
        gcloud services enable firebase.googleapis.com --project="$(cat /workspace/SOCCER_PROJECT_ID.txt)"

  # Step 3: Install Firebase CLI
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "⬇️ Installing Firebase CLI..."
        
        curl -sL https://firebase.tools | bash

        mkdir -p /workspace/firebase
        cp /usr/local/bin/firebase /workspace/firebase/
        chmod +x /workspace/firebase/firebase

        echo "🔍 Verifying Firebase CLI installation..."
        if ! /workspace/firebase/firebase --version; then
          echo "❌ Error: Firebase CLI installation failed."
          exit 1
        fi
        echo "✅ Firebase CLI installed successfully!"

  # Step 4: Prepare Firebase Project Files
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "📂 Creating Firebase project directory..."
        rm -rf /workspace/firebase_project
        mkdir -p /workspace/firebase_project

        # ✅ Corrected the path here:
        cp /workspace/gcp/cloud-build/firebase.json /workspace/firebase_project/firebase.json

  # Step 5: Enable Firebase Authentication API
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "🔑 Enabling Firebase Authentication API..."
        gcloud services enable identitytoolkit.googleapis.com --project="$(cat /workspace/SOCCER_PROJECT_ID.txt)"

  # Step 6: Configure Email/Password Authentication directly from firebase.json
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "⚙️ Configuring Email/Password sign-in provider from firebase.json..."

        PROJECT_ID=$(cat /workspace/SOCCER_PROJECT_ID.txt)

        curl -X PATCH \
          -H "Authorization: Bearer $(gcloud auth print-access-token)" \
          -H "Content-Type: application/json" \
          --data-binary @/workspace/firebase_project/firebase.json \
          "https://identitytoolkit.googleapis.com/admin/v2/projects/${PROJECT_ID}/config"

        echo "✅ Email/Password Authentication configured using firebase.json!"

options:
  logging: CLOUD_LOGGING_ONLY
