substitutions:
  _ENVIRONMENT: 'dev'                         # Environment delivered from the trigger
  _FOLDER_NAME: 'soccer'                      # Parent folder name

steps:
  # Step 1: Retrieve the project ID
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "Checking if project starting with ${_FOLDER_NAME}-${_ENVIRONMENT} exists..."
        gcloud projects list \
          --filter="name~^${_FOLDER_NAME}-${_ENVIRONMENT}" \
          --format="value(projectId)" | head -n 1 > /workspace/SOCCER_PROJECT_ID.txt

        if [ ! -s /workspace/SOCCER_PROJECT_ID.txt ] || [ -z "$(cat /workspace/SOCCER_PROJECT_ID.txt)" ]; then
          echo "❌ Error: Project ID not found. Ensure the project exists."
          exit 1
        fi
        echo "✅ Using project: $(cat /workspace/SOCCER_PROJECT_ID.txt)"

  # Step 2: Enable Firebase in the project
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "🔓 Enabling Firebase in project $(cat /workspace/SOCCER_PROJECT_ID.txt)..."
        gcloud services enable firebase.googleapis.com --project="$(cat /workspace/SOCCER_PROJECT_ID.txt)"

  # Step 3: Register the project with Firebase via API (Handle 409 gracefully)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "📡 Registering project $(cat /workspace/SOCCER_PROJECT_ID.txt) with Firebase..."

        # Get the access token
        access_token=$(gcloud auth print-access-token)

        # Make the API call
        response_code=$(curl -s -o response.json -w "%{http_code}" -X POST \
            -H "Authorization: Bearer ${access_token}" \
            -H "Content-Type: application/json" \
            -d '{}' \
            "https://firebase.googleapis.com/v1beta1/projects/$(cat /workspace/SOCCER_PROJECT_ID.txt):addFirebase")

        # Handle API responses
        if [ "$response_code" -eq 200 ]; then
          echo "✅ Firebase project registered successfully!"
        elif [ "$response_code" -eq 409 ]; then
          echo "⚠️ Firebase project already registered. Continuing with deployment..."
        else
          echo "❌ Error registering Firebase project. Response code: $response_code"
          cat response.json
          exit 1
        fi

  # Step 4: Install Firebase CLI in a Persistent Directory
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "⬇️ Installing Firebase CLI..."
        
        # Install Firebase CLI
        curl -sL https://firebase.tools | bash

        # Move the binary to a persistent location
        mkdir -p /workspace/firebase
        cp /usr/local/bin/firebase /workspace/firebase/
        chmod +x /workspace/firebase/firebase

        echo "🔍 Verifying Firebase CLI installation..."
        if ! /workspace/firebase/firebase --version; then
          echo "❌ Error: Firebase CLI installation failed."
          exit 1
        fi
        echo "✅ Firebase CLI installed successfully!"

  # Step 5: Prepare Firebase Project Files
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "📂 Creating Firebase project directory..."
        rm -rf /workspace/firebase_project
        mkdir -p /workspace/firebase_project
        cd /workspace/firebase_project

        echo "📥 Copying Firebase configuration files..."
        cp /workspace/gcp/cloud-build/firebase.json .
        cp /workspace/gcp/cloud-build/.firebaserc .
        cp /workspace/gcp/cloud-build/firestore.rules .
        cp /workspace/gcp/cloud-build/database.rules.json .
        cp /workspace/gcp/cloud-build/storage.rules .

        # Ensure project ID is updated in .firebaserc
        sed -i "s/SOCCER_PROJECT_ID/$(cat /workspace/SOCCER_PROJECT_ID.txt)/g" .firebaserc
        if ! grep -q "$(cat /workspace/SOCCER_PROJECT_ID.txt)" .firebaserc; then
          echo "❌ Error: Project ID substitution failed in .firebaserc"
          exit 1
        fi
        echo "✅ Project ID substitution successful in .firebaserc"

  # Step 6: Initialize Realtime Database if not exists
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "🔍 Checking for existing Realtime Database instance..."

        # Project ID and Access Token
        project_id=$(cat /workspace/SOCCER_PROJECT_ID.txt)
        access_token=$(gcloud auth print-access-token)

        # Enable Realtime Database API
        echo "⚙️ Enabling Realtime Database API..."
        gcloud services enable firebasedatabase.googleapis.com --project="$project_id"

        # Check if Realtime Database exists
        response=$(curl -s -H "Authorization: Bearer ${access_token}" \
          "https://firebasedatabase.googleapis.com/v1/projects/${project_id}/locations/-/instances")

        if echo "$response" | grep -q '"instances":'; then
          echo "✅ Realtime Database already exists. Skipping initialization."
        else
          echo "⚠️ Realtime Database not found. Creating a new instance..."

          # Correct API to create a Realtime Database instance
          create_response=$(curl -s -X POST -H "Authorization: Bearer ${access_token}" \
            -H "Content-Type: application/json" \
            -d '{
                  "database": {
                    "type": "DEFAULT_DATABASE",
                    "locationId": "us-central1"
                  }
                }' \
            "https://firebasedatabase.googleapis.com/v1/projects/${project_id}/locations/us-central1/instances")

          if echo "$create_response" | grep -q '"name":'; then
            echo "✅ Realtime Database instance created successfully!"
          else
            echo "❌ Failed to create Realtime Database instance."
            echo "$create_response"
            exit 1
          fi
        fi

  # Step 7: Deploy Firebase Configuration Using Shared CLI
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "🚀 Deploying Firebase configuration to $(cat /workspace/SOCCER_PROJECT_ID.txt)..."

        # Use the Firebase CLI installed in /workspace/firebase
        if ! /workspace/firebase/firebase --version; then
          echo "❌ Error: Firebase CLI is not available."
          exit 1
        fi

        cd /workspace/firebase_project
        /workspace/firebase/firebase deploy --project="$(cat /workspace/SOCCER_PROJECT_ID.txt)"

options:
  logging: CLOUD_LOGGING_ONLY
