# deploy_realtime_db_locked.yaml
substitutions:
  _ENVIRONMENT: 'dev'
  _FOLDER_NAME: 'soccer'

steps:
# 0. Resolve Firebase project ID & number
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: 'get-project-info'
  entrypoint: bash
  args:
    - '-c'
    - |
      set -ex
      # project ID
      gcloud projects list \
        --filter="name~^${_FOLDER_NAME}-${_ENVIRONMENT}" \
        --format="value(projectId)" | head -n1 \
        > /workspace/firebase_project_id.txt
      test -s /workspace/firebase_project_id.txt

      # project number
      project_id=$(< /workspace/firebase_project_id.txt)
      gcloud projects describe "$project_id" \
        --format="value(projectNumber)" \
        > /workspace/firebase_project_number.txt
      test -s /workspace/firebase_project_number.txt

# 1. Grant Firebasedatabase.Admin + TokenCreator on the Admin SDK SA
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: 'grant-db-admin-and-token-creator'
  entrypoint: bash
  args:
    - '-c'
    - |
      set -ex
      project=$(< /workspace/firebase_project_id.txt)

      # 1a) Who am I right now?
      build_sa=$(gcloud auth list --filter=status:ACTIVE --format="value(account)")

      # 1b) The special Firebase Admin SDK service account in your project:
      admin_sa="firebase-adminsdk-fbsvc@${project}.iam.gserviceaccount.com"

      # Grant it the DB admin role
      gcloud projects add-iam-policy-binding "$project" \
        --member="serviceAccount:${build_sa}" \
        --role="roles/firebasedatabase.admin" \
        --quiet

      # Allow the build SA to impersonate it
      gcloud iam service-accounts add-iam-policy-binding \
        "$admin_sa" \
        --member="serviceAccount:${build_sa}" \
        --role="roles/iam.serviceAccountTokenCreator" \
        --quiet


# 2. Enable the Realtime Database Management API
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: 'enable-rtdb-api'
  entrypoint: bash
  args:
    - '-c'
    - |
      set -ex
      project=$(< /workspace/firebase_project_id.txt)
      gcloud services enable firebasedatabase.googleapis.com \
        --project="$project" --quiet

# 3. Small delay to let IAM & service enablement propagate
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: 'wait-for-propagation'
  entrypoint: bash
  args:
    - '-c'
    - |
      set -ex
      echo "⏳ Waiting 15s for IAM & API enablement to propagate..."
      sleep 15

# 4. Clone your source (to pull in firebase.json & database.rules.json)
- name: 'gcr.io/cloud-builders/git'
  id: 'pull-source'
  entrypoint: bash
  args:
    - '-c'
    - |
      set -ex
      git clone -b development --single-branch \
        https://github.com/piotr-gorczynski/Soccer.git /workspace/soccer
      cp /workspace/soccer/gcp/cloud-build/firebase.json    /workspace/firebase.json
      cp /workspace/soccer/gcp/cloud-build/database.rules.json /workspace/database.rules.json

# 5. Install Firebase CLI
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: 'install-firebase-cli'
  entrypoint: bash
  args:
    - '-c'
    - |
      set -ex
      curl -sL https://firebase.tools | bash
      mkdir -p /workspace/firebase
      cp /usr/local/bin/firebase /workspace/firebase/
      chmod +x /workspace/firebase/firebase

# 6. Create the default RTDB via Management REST API
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: 'create-default-rtdb'
  entrypoint: bash
  args:
    - '-c'
    - |
      set -ex
      project=$(< /workspace/firebase_project_id.txt)
      project_number=$(gcloud projects describe "$project" --format="value(projectNumber)")
      inst="${project}-default-rtdb"
      loc="us-central1"

      echo "🚀 Creating default RTDB instance $inst in $loc by impersonating $admin_sa…"

      # Mint a token as the Admin-SDK SA
      token=$(gcloud auth print-access-token \
        --impersonate-service-account="firebase-adminsdk-fbsvc@${project}.iam.gserviceaccount.com")

      # Call the Management API
      response=$(curl -s -w '\n%{http_code}' -X POST \
        -H "Authorization: Bearer $token" \
        "https://firebasedatabase.googleapis.com/v1beta/projects/${project_number}/locations/${loc}/instances?databaseId=${inst}")

      code=$(echo "$response" | tail -n1)
      body=$(echo "$response" | sed '$d')

      if [[ "$code" == "200" ]]; then
        echo "✅ RTDB created:"; echo "$body"
      elif [[ "$code" == "409" ]]; then
        echo "✅ RTDB already exists."
      else
        echo "❌ RTDB creation failed (HTTP $code):"; echo "$body"
        exit 1
      fi

# 7. Deploy locked-mode rules via firebase.json
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: 'deploy-locked-rules'
  entrypoint: bash
  args:
    - '-c'
    - |
      set -ex
      project=$(< /workspace/firebase_project_id.txt)
      cd /workspace
      /workspace/firebase/firebase deploy \
        --only database \
        --project "$project" \
        --force

options:
  logging: CLOUD_LOGGING_ONLY
