substitutions:
  _ENVIRONMENT: 'dev'
  _FOLDER_NAME: 'soccer'

steps:
  # Step 1: Get Firebase project ID
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'get-project-id'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        echo "🔎 Finding project for ${_FOLDER_NAME}-${_ENVIRONMENT}..."
        gcloud projects list \
          --filter="name~^${_FOLDER_NAME}-${_ENVIRONMENT}" \
          --format="value(projectId)" \
          | head -n 1 > /workspace/FIREBASE_PROJECT_ID.txt

        if [ ! -s /workspace/FIREBASE_PROJECT_ID.txt ]; then
          echo "❌ Project ID not found!"
          exit 1
        fi

  # Step 2 – download stand-alone Firebase CLI (no Node needed later)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: install-firebase-cli
    entrypoint: bash
    args:
      - -c
      - |
        set -ex
        echo "⬇️  Downloading Firebase CLI binary…"
        curl -sL https://firebase.tools | bash      # ➜ puts binary in /usr/local/bin

        echo "ℹ️  CLI version: $(firebase --version)"

        mkdir -p /workspace/firebase                # copy for later steps
        cp "$(command -v firebase)" /workspace/firebase/firebase
        chmod +x /workspace/firebase/firebase
        echo "✅  Firebase CLI ready (stand-alone)."

  # Step 3: Clone source code
  - name: 'gcr.io/cloud-builders/git'
    id: 'pull-files'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -ex
        echo "📦 Cloning from the development branch..."
        git clone -b development --single-branch https://github.com/piotr-gorczynski/Soccer.git /workspace/soccer

        echo "📁 Copying Firestore config & change-player-turn function..."
        cp /workspace/soccer/firebase/firebase.json /workspace/firebase/firebase.json
        cp /workspace/soccer/firebase/firestore.rules /workspace/firebase/firestore.rules

        mkdir -p /workspace/firebase/functions/change-player-turn
        cp /workspace/soccer/firebase/functions/change-player-turn/package.json /workspace/firebase/functions/change-player-turn/
        cp /workspace/soccer/firebase/functions/change-player-turn/index.js /workspace/firebase/functions/change-player-turn/

  # Step 4: Install dependencies
  - name: 'node:18-slim'
    id: 'install-deps-change-player-turn'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -ex
        cd /workspace/firebase/functions/change-player-turn
        npm install
        echo "📦 Dependencies installed."

  # Step 5 – deploy using the binary copied in Step 2
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: deploy-change-player-turn
    entrypoint: bash
    args:
      - -c
      - |
        set -ex
        cd /workspace/firebase
        project_id=$(cat /workspace/FIREBASE_PROJECT_ID.txt)

        ./firebase deploy \
          --only functions:change-player-turn \
          --project="$project_id" \
          --force --non-interactive

        echo "✅ changePlayerTurn deployed."



options:
  logging: CLOUD_LOGGING_ONLY
