substitutions:
  _ENVIRONMENT: 'dev'
  _FOLDER_NAME: 'soccer'

steps:
  # Step 0: Retrieve the Firebase project ID
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        echo "📦 Looking for Firebase project starting with ${_FOLDER_NAME}-${_ENVIRONMENT}..."
        gcloud projects list \
          --filter="name~^${_FOLDER_NAME}-${_ENVIRONMENT}" \
          --format="value(projectId)" \
          | head -n 1 > /workspace/SOCCER_PROJECT_ID.txt

        if [ ! -s /workspace/SOCCER_PROJECT_ID.txt ]; then
          echo "❌ Firebase project not found."
          exit 1
        fi

        echo "✅ Found Firebase project: $(cat /workspace/SOCCER_PROJECT_ID.txt)"

  # Step 1: Generate an access token
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        access_token=$(gcloud auth print-access-token)
        echo "$access_token" > /workspace/access_token.txt
        echo "🔑 Access token generated and stored."

  # Step 2: Initialize Identity Platform (create the Auth config)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        firebase_project_id=$(cat /workspace/SOCCER_PROJECT_ID.txt)
        access_token=$(cat /workspace/access_token.txt)

        echo "🚀 Initializing Identity Platform for project: $firebase_project_id..."
        response=$(curl -s -w '\n%{http_code}' -X POST \
          -H "Authorization: Bearer $access_token" \
          -H "Content-Type: application/json" \
          -H "X-Goog-User-Project: $firebase_project_id" \
          "https://identitytoolkit.googleapis.com/v2/projects/$firebase_project_id/identityPlatform:initializeAuth")

        http_code=$(echo "$response" | tail -n1)
        body=$(echo "$response" | head -n-1)

        if [[ "$http_code" == "200" ]]; then
          echo "✅ Identity Platform initialized."
        elif echo "$body" | grep -q "Identity Platform has already been enabled for this project."; then
          echo "✅ Identity Platform is already enabled. Skipping."
        else
          echo "❌ Failed to initialize Identity Platform. Response code: $http_code"
          echo "Response body:"
          echo "$body"
          exit 1
        fi

  # Step 3: Enable Email/Password Auth
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        firebase_project_id=$(cat /workspace/SOCCER_PROJECT_ID.txt)
        access_token=$(cat /workspace/access_token.txt)

        echo "🔑 Attempting to enable Email/Password authentication..."
        patch_response=$(curl -s -w '\n%{http_code}' -X PATCH \
          -H "Authorization: Bearer $access_token" \
          -H "X-Goog-User-Project: $firebase_project_id" \
          -H "Content-Type: application/json" \
          "https://identitytoolkit.googleapis.com/admin/v2/projects/$firebase_project_id/config?updateMask=signIn.email" \
          -d '{
            "signIn": {
              "email": {
                "enabled": true,
                "passwordRequired": true
              }
            }
          }')

        patch_code=$(echo "$patch_response" | tail -n1)
        patch_body=$(echo "$patch_response" | head -n-1)

        if [[ "$patch_code" == "200" ]]; then
          echo "✅ Email/Password sign-in successfully enabled."
          echo "$patch_body"
        else
          echo "❌ Failed to enable Email/Password authentication. HTTP $patch_code"
          echo "Response body:"
          echo "$patch_body"
          exit 1
        fi

  # ────────────────────────────────
  # Step 4: Enable Google Sign-In
  # ────────────────────────────────
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: enable-google-auth
    entrypoint: bash
    args:
      - '-c'
      - |
        set -ex

        firebase_project_id=$(cat /workspace/SOCCER_PROJECT_ID.txt)
        access_token=$(cat /workspace/access_token.txt)

        echo "🔐 Retrieving secrets from Secret Manager (org-service-account-001)…"

        gcloud secrets versions access latest \
          --secret=google-client-id \
          --project="690882718361" | tr -d '\n' > /workspace/google-client-id.txt

        gcloud secrets versions access latest \
          --secret=google-client-secret \
          --project="690882718361" | tr -d '\n' > /workspace/google-client-secret.txt

        if [ ! -s /workspace/google-client-id.txt ] || [ -z "$(cat /workspace/google-client-id.txt)" ]; then
          echo "❌ Error: Failed to retrieve google-client-id"
          exit 1
        fi

        if [ ! -s /workspace/google-client-secret.txt ] || [ -z "$(cat /workspace/google-client-secret.txt)" ]; then
          echo "❌ Error: Failed to retrieve google-client-secret"
          exit 1
        fi

        client_id=$(cat /workspace/google-client-id.txt)
        client_secret=$(cat /workspace/google-client-secret.txt)

        echo "🔓 Enabling Google Sign-In for project: $firebase_project_id"

        # PATCH first in case config already exists
        patch_resp=$(curl -s -o /dev/null -w '%{http_code}' -X PATCH \
          -H "Authorization: Bearer $access_token" \
          -H "X-Goog-User-Project: $firebase_project_id" \
          -H "Content-Type: application/json" \
          "https://identitytoolkit.googleapis.com/admin/v2/projects/$firebase_project_id/defaultSupportedIdpConfigs/google.com?updateMask=enabled,clientId,clientSecret" \
          -d '{
                "enabled": true,
                "clientId": "'"$client_id"'",
                "clientSecret": "'"$client_secret"'"
              }')

        if [[ "$patch_resp" == "200" ]]; then
          echo "✅ Google Sign-In provider updated."
          exit 0
        fi

        # If PATCH failed because provider doesn’t exist, try POST
        echo "ℹ️  Trying to create Google provider…"

        create_resp=$(curl -s -w '\n%{http_code}' -X POST \
          -H "Authorization: Bearer $access_token" \
          -H "X-Goog-User-Project: $firebase_project_id" \
          -H "Content-Type: application/json" \
          "https://identitytoolkit.googleapis.com/admin/v2/projects/$firebase_project_id/defaultSupportedIdpConfigs?idpId=google.com" \
          -d '{
                "enabled": true,
                "clientId": "'"$client_id"'",
                "clientSecret": "'"$client_secret"'"
              }')

        create_code=$(echo "$create_resp" | tail -n1)

        if [[ "$create_code" == "200" ]]; then
          echo "✅ Google Sign-In provider created."
        else
          echo "❌ Failed to create provider (HTTP $create_code):"
          echo "$create_resp"
          exit 1
        fi

options:
  logging: CLOUD_LOGGING_ONLY
