# ──────────────────────────────────────────────────────────────
#  deploy_firestore_indexes.yaml
#  Pushes firestore.indexes.json (and nothing else)
# ──────────────────────────────────────────────────────────────
substitutions:
  _ENVIRONMENT: 'dev'          # ← keep the same values
  _FOLDER_NAME: 'soccer'       # ←   you already use

steps:
  # 1️⃣  Resolve the Firebase project ID that matches
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'get-project-id'
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        echo "🔍 Getting project ID for ${_FOLDER_NAME}-${_ENVIRONMENT}…"
        gcloud projects list \
          --filter="name~^${_FOLDER_NAME}-${_ENVIRONMENT}" \
          --format="value(projectId)" \
          | head -n 1 > /workspace/FIREBASE_PROJECT_ID.txt

        if [[ ! -s /workspace/FIREBASE_PROJECT_ID.txt ]]; then
          echo "❌ Firebase project not found."
          exit 1
        fi

  # 2️⃣  Install Firebase CLI once per build layer
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'install-firebase-cli'
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        curl -sL https://firebase.tools | bash          # single-line installer
        mkdir -p /workspace/firebase
        cp /usr/local/bin/firebase /workspace/firebase/
        chmod +x /workspace/firebase/firebase
        echo "✅ Firebase CLI installed."

  # 3️⃣  Clone your repo and copy only the artefacts we need
  - name: 'gcr.io/cloud-builders/git'
    id: 'clone-repo'
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        echo "🔁 Cloning development branch…"
        git clone -b development --single-branch \
          https://github.com/piotr-gorczynski/Soccer.git /workspace/soccer

        echo "📂 Copying Firestore indexes & firebase.json…"
        mkdir -p /workspace/firebase
        cp /workspace/soccer/firebase/firestore.indexes.json /workspace/firebase/
        cp /workspace/soccer/firebase/firebase.json        /workspace/firebase/

  # 4️⃣  Deploy the indexes (nothing else)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'deploy-firestore-indexes'
    entrypoint: bash
    args:
      - -c
      - |
        set -e
        cd /workspace/firebase
        project_id=$(cat /workspace/FIREBASE_PROJECT_ID.txt)
        echo "🚀 Deploying Firestore INDEXES to $project_id"
        ./firebase deploy \
          --only firestore:indexes \
          --project="$project_id" \
          --force
        echo "✅ Indexes deployed."

options:
  logging: CLOUD_LOGGING_ONLY
