# deploy_realtime_db_locked.yaml
substitutions:
  _ENVIRONMENT: 'dev'
  _FOLDER_NAME: 'soccer'

steps:
# 0. Resolve Firebase project ID
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: 'get-project-id'
  entrypoint: bash
  args:
    - '-c'
    - |
      set -e
      gcloud projects list \
        --filter="name~^${_FOLDER_NAME}-${_ENVIRONMENT}" \
        --format="value(projectId)" \
        | head -n1 > /workspace/FIREBASE_PROJECT_ID.txt
      test -s /workspace/FIREBASE_PROJECT_ID.txt

# 1. Clone your source (to pull in firebase.json & database.rules.json)
- name: 'gcr.io/cloud-builders/git'
  id: 'pull-source'
  entrypoint: bash
  args:
    - '-c'
    - |
      set -e
      git clone -b development --single-branch \
        https://github.com/piotr-gorczynski/Soccer.git /workspace/soccer
      cp /workspace/soccer/gcp/cloud-build/firebase.json  /workspace/firebase.json
      cp /workspace/soccer/gcp/cloud-build/database.rules.json /workspace/database.rules.json

# 2. Install Firebase CLI
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: 'install-firebase-cli'
  entrypoint: bash
  args:
    - '-c'
    - |
      set -e
      echo "⬇️ Installing Firebase CLI..."
      curl -sL https://firebase.tools | bash
      mkdir -p /workspace/firebase
      cp /usr/local/bin/firebase /workspace/firebase/
      chmod +x /workspace/firebase/firebase
      echo "✅ Firebase CLI installed."

# 3. Create the *default* RTDB in us-central1
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: 'create-default-rtdb'
  entrypoint: bash
  args:
    - '-c'
    - |
      set -e
      project_id=$(cat /workspace/FIREBASE_PROJECT_ID.txt)
      instance="$project_id"   # default instance ID = projectId
      echo "🚀 Creating default RTDB $instance in us-central1…"
      /workspace/firebase/firebase database:instances:create "$instance" \
        --location us-central1 \
        --project "$project_id" \
      || echo "ℹ️ Instance already exists."

# 4. Deploy *locked-mode* rules from your checked-in file
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  id: 'deploy-locked-rules'
  entrypoint: bash
  args:
    - '-c'
    - |
      set -e
      project_id=$(cat /workspace/FIREBASE_PROJECT_ID.txt)
      cd /workspace               # root now has firebase.json & database.rules.json
      echo "🔒 Deploying locked-mode rules…"
      /workspace/firebase/firebase deploy \
        --only database \
        --project "$project_id" \
        --force

options:
  logging: CLOUD_LOGGING_ONLY
