substitutions:
  _ENVIRONMENT: 'dev'
  _FOLDER_NAME: 'soccer'

steps:
  # Step 1: Get Firebase project ID
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'get-project-id'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        echo "🔎 Finding project for ${_FOLDER_NAME}-${_ENVIRONMENT}..."
        gcloud projects list \
          --filter="name~^${_FOLDER_NAME}-${_ENVIRONMENT}" \
          --format="value(projectId)" \
          | head -n 1 > /workspace/FIREBASE_PROJECT_ID.txt

        if [ ! -s /workspace/FIREBASE_PROJECT_ID.txt ]; then
          echo "❌ Project ID not found!"
          exit 1
        fi

  # Step 2 – install latest Firebase CLI in a Node container
  - name: 'node:20-slim'            # 👈 has npm pre-installed
    id: install-firebase-cli
    entrypoint: bash
    args:
      - -c
      - |
        set -ex
        echo "⬇️  Installing Firebase CLI..."
        npm install -g firebase-tools@latest
        firebase --version           # sanity-check
        # copy binary so later steps (which use cloud-sdk) can call it
        mkdir -p /workspace/firebase
        cp "$(command -v firebase)" /workspace/firebase/
        chmod +x /workspace/firebase/firebase
        echo "✅  Firebase CLI installed."

  # Step 3: Clone source code
  - name: 'gcr.io/cloud-builders/git'
    id: 'pull-files'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -ex
        echo "📦 Cloning from the development branch..."
        git clone -b development --single-branch https://github.com/piotr-gorczynski/Soccer.git /workspace/soccer

        echo "📁 Copying Firestore config & change-player-turn function..."
        cp /workspace/soccer/firebase/firebase.json /workspace/firebase/firebase.json
        cp /workspace/soccer/firebase/firestore.rules /workspace/firebase/firestore.rules

        mkdir -p /workspace/firebase/functions/change-player-turn
        cp /workspace/soccer/firebase/functions/change-player-turn/package.json /workspace/firebase/functions/change-player-turn/
        cp /workspace/soccer/firebase/functions/change-player-turn/index.js /workspace/firebase/functions/change-player-turn/

  # Step 4: Install dependencies
  - name: 'node:18-slim'
    id: 'install-deps-change-player-turn'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -ex
        cd /workspace/firebase/functions/change-player-turn
        npm install
        echo "📦 Dependencies installed."

  # Step 5: Deploy function (Cloud SDK + Node runtime inside)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:nodejs20'
    id: 'deploy-change-player-turn'
    entrypoint: bash
    args:
      - -c
      - |
        set -ex
        cd /workspace/firebase
        project_id=$(cat /workspace/FIREBASE_PROJECT_ID.txt)

        /workspace/firebase/firebase deploy \
          --only functions:change-player-turn \
          --project="${project_id}" \
          --force --non-interactive

        echo "✅ Function 'changePlayerTurn' deployed successfully."

  # Step 6: Add IAM policy binding to allow allUsers to invoke
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'bind-invoker-role'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        project_id=$(cat /workspace/FIREBASE_PROJECT_ID.txt)

        echo "🔐 Granting invoker role to allUsers for 'changePlayerTurn'..."
        gcloud functions add-iam-policy-binding changePlayerTurn \
          --region=us-central1 \
          --project="$project_id" \
          --member="allUsers" \
          --role="roles/cloudfunctions.invoker"

        echo "✅ IAM policy binding applied."

options:
  logging: CLOUD_LOGGING_ONLY
