substitutions:
  _ENVIRONMENT: 'dev'
  _FOLDER_NAME: 'soccer'

steps:
  # Step 1: Get Firebase Project ID
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'get-project-id'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "🔍 Looking for project starting with ${_FOLDER_NAME}-${_ENVIRONMENT}..."
        gcloud projects list \
          --filter="name~^${_FOLDER_NAME}-${_ENVIRONMENT}" \
          --format="value(projectId)" | head -n 1 > /workspace/project_id.txt

        if [ ! -s /workspace/project_id.txt ]; then
          echo "❌ Firebase project not found."
          exit 1
        fi

        echo "✅ Found project ID: $(cat /workspace/project_id.txt)"

  # Step 2: Just log IAM roles for Cloud Build SA (no API enabling anymore)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'log-sa-roles'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        firebase_project_id=$(cat /workspace/project_id.txt)
        cloud_build_sa="cloud-build-sa@org-service-account-001.iam.gserviceaccount.com"

        echo "🔍 Listing roles for Cloud Build SA on project: $firebase_project_id"
        gcloud projects get-iam-policy "$firebase_project_id" \
          --flatten="bindings[].members" \
          --filter="bindings.members:$cloud_build_sa" \
          --format="table(bindings.role)"

  # Step 3: Write Terraform config using correct resource
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'write-tf-config'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        mkdir -p /workspace/tf-auth

        # main.tf
        cat <<EOF > /workspace/tf-auth/main.tf
        terraform {
          required_providers {
            google-beta = {
              source  = "hashicorp/google-beta"
              version = ">= 4.80.0"
            }
          }
        }

        provider "google-beta" {
          project = var.project_id
          region  = "us-central1"
        }

        resource "google_identity_platform_config" "default" {
          project = var.project_id

          sign_in {
            email {
              enabled = true
            }
            anonymous {
              enabled = false
            }
            phone_number {
              enabled = false
            }
          }
        }
        EOF

        # variables.tf
        cat <<EOF > /workspace/tf-auth/variables.tf
        variable "project_id" {
          type = string
        }
        EOF

  # Step 4: Terraform Init
  - name: 'hashicorp/terraform:light'
    id: 'terraform-init'
    dir: '/workspace/tf-auth'
    entrypoint: 'sh'
    args: ['-c', 'terraform init']

  # Step 5: Terraform Apply with project_id var
  - name: 'hashicorp/terraform:light'
    id: 'terraform-apply'
    dir: '/workspace/tf-auth'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform apply -auto-approve -var="project_id=$(cat /workspace/project_id.txt)"

options:
  logging: CLOUD_LOGGING_ONLY
