substitutions:
  _ENVIRONMENT: 'dev'
  _FOLDER_NAME: 'soccer'

steps:
  # Step 0: Retrieve the Firebase project ID
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        echo "📦 Looking for Firebase project starting with ${_FOLDER_NAME}-${_ENVIRONMENT}..."
        gcloud projects list \
          --filter="name~^${_FOLDER_NAME}-${_ENVIRONMENT}" \
          --format="value(projectId)" \
          | head -n 1 > /workspace/SOCCER_PROJECT_ID.txt

        if [ ! -s /workspace/SOCCER_PROJECT_ID.txt ]; then
          echo "❌ Firebase project not found."
          exit 1
        fi

        echo "✅ Found Firebase project: $(cat /workspace/SOCCER_PROJECT_ID.txt)"

  # Step 1: Generate an access token
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        access_token=$(gcloud auth print-access-token)
        echo "$access_token" > /workspace/access_token.txt
        echo "🔑 Access token generated and stored."

  # Step 2: Initialize Identity Platform (create the Auth config)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        firebase_project_id=$(cat /workspace/SOCCER_PROJECT_ID.txt)
        access_token=$(cat /workspace/access_token.txt)

        echo "🚀 Initializing Identity Platform for project: $firebase_project_id..."
        response=$(curl -s -w '\n%{http_code}' -X POST \
          -H "Authorization: Bearer $access_token" \
          -H "Content-Type: application/json" \
          -H "X-Goog-User-Project: $firebase_project_id" \
          "https://identitytoolkit.googleapis.com/v2/projects/$firebase_project_id/identityPlatform:initializeAuth")

        http_code=$(echo "$response" | tail -n1)
        body=$(echo "$response" | head -n-1)

        if [[ "$http_code" == "200" ]]; then
          echo "✅ Identity Platform initialized."
        elif echo "$body" | grep -q "Identity Platform has already been enabled for this project."; then
          echo "✅ Identity Platform is already enabled. Skipping."
        else
          echo "❌ Failed to initialize Identity Platform. Response code: $http_code"
          echo "Response body:"
          echo "$body"
          exit 1
        fi

  # Step 3: Enable Email/Password Auth
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        firebase_project_id=$(cat /workspace/SOCCER_PROJECT_ID.txt)
        access_token=$(cat /workspace/access_token.txt)

        echo "🔑 Attempting to enable Email/Password authentication..."
        patch_response=$(curl -s -w '\n%{http_code}' -X PATCH \
          -H "Authorization: Bearer $access_token" \
          -H "X-Goog-User-Project: $firebase_project_id" \
          -H "Content-Type: application/json" \
          "https://identitytoolkit.googleapis.com/admin/v2/projects/$firebase_project_id/config?updateMask=signIn.email" \
          -d '{
            "signIn": {
              "email": {
                "enabled": true,
                "passwordRequired": true
              }
            }
          }')

        patch_code=$(echo "$patch_response" | tail -n1)
        patch_body=$(echo "$patch_response" | head -n-1)

        if [[ "$patch_code" == "200" ]]; then
          echo "✅ Email/Password sign-in successfully enabled."
          echo "$patch_body"
        else
          echo "❌ Failed to enable Email/Password authentication. HTTP $patch_code"
          echo "Response body:"
          echo "$patch_body"
          exit 1
        fi

  # ────────────────────────────────
  # Step 4:  Enable Google Sign-In
  # ────────────────────────────────
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'enable-google-auth'
    entrypoint: bash
    # Optional: surface your own OAuth client to Identity Platform.
    # Pass them in as Cloud Build substitution variables or pull from Secret Manager.
    env:
      - 'GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID:-}'
      - 'GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET:-}'
    args:
      - '-c'
      - |
        set -e
        firebase_project_id=$(cat /workspace/SOCCER_PROJECT_ID.txt)
        access_token=$(cat /workspace/access_token.txt)

        echo "🔓 Enabling Google Sign-In …"

        # Build the JSON payload: if you supplied a custom OAuth client,
        # include it; otherwise rely on the Google-managed default.
        body='{"enabled":true'
        if [[ -n "$GOOGLE_CLIENT_ID" && -n "$GOOGLE_CLIENT_SECRET" ]]; then
          body=$body', "clientId":"'"$GOOGLE_CLIENT_ID"'", "clientSecret":"'"$GOOGLE_CLIENT_SECRET"'"'
          updateMask="enabled,clientId,clientSecret"
        else
          updateMask="enabled"
        fi
        body=$body'}'

        target="https://identitytoolkit.googleapis.com/admin/v2/projects/${firebase_project_id}/defaultSupportedIdpConfigs/google.com?updateMask=${updateMask}"

        # First try PATCH (fast path if the config already exists) …
        response=$(curl -s -w '\n%{http_code}' \
          -X PATCH "$target" \
          -H "Authorization: Bearer $access_token" \
          -H "X-Goog-User-Project: $firebase_project_id" \
          -H "Content-Type: application/json" \
          -d "$body")

        code=$(echo "$response" | tail -n1)
        body_json=$(echo "$response" | head -n-1)

        if [[ "$code" == "200" ]]; then
          echo "✅ Google provider updated."
          exit 0
        fi

        # … otherwise create the config from scratch.
        if echo "$body_json" | grep -q "CONFIGURATION_NOT_FOUND"; then
          echo "ℹ️  Google provider missing – creating."
          create_resp=$(curl -s -w '\n%{http_code}' \
            -X POST "https://identitytoolkit.googleapis.com/admin/v2/projects/${firebase_project_id}/defaultSupportedIdpConfigs?idpId=google.com" \
            -H "Authorization: Bearer $access_token" \
            -H "X-Goog-User-Project: $firebase_project_id" \
            -H "Content-Type: application/json" \
            -d "$body")

          [[ "$(echo "$create_resp" | tail -n1)" == "200" ]] && {
            echo "✅ Google Sign-In enabled."
          } || {
            echo "❌ Failed to create Google provider:"; echo "$create_resp"; exit 1;
          }
        else
          echo "❌ Failed to enable Google provider (HTTP $code)."
          echo "$body_json"
          exit 1
        fi

options:
  logging: CLOUD_LOGGING_ONLY
