substitutions:
  _SECRET_NAME: 'soccer_secret_key'
  _SECRET_PROJECT: '690882718361'
  _PRIVATE_REPO: 'git@github.com:piotr-gorczynski/Soccer-private.git'
  _BRANCH_NAME: 'main'
  _TARGET_PATH: 'soccer_secret_key'  # Save in root folder of private repo

availableSecrets:
  secretManager:
    - versionName: projects/org-service-account-001/secrets/github_ssh_key_soccer_private/versions/latest
      env: 'ssh_private_key'

steps:
  # Step 1: Retrieve the secret value
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'get-secret'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        set -x
        gcloud secrets versions access latest \
          --secret="${_SECRET_NAME}" \
          --project="${_SECRET_PROJECT}" | tr -d '\n' > /workspace/${_TARGET_PATH}

  # Step 2: Clone private repo
  - name: 'gcr.io/cloud-builders/git'
    id: 'clone-repo'
    secretEnv: ['ssh_private_key']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        set -x
        mkdir -p /root/.ssh
        echo "$ssh_private_key" > /root/.ssh/id_ed25519
        chmod 400 /root/.ssh/id_ed25519
        ssh-keyscan github.com >> /root/.ssh/known_hosts

        git config --global user.email "ci-bot@soccer.dev"
        git config --global user.name "CI Bot"

        git clone ${_PRIVATE_REPO} /workspace/private-repo
        cp /workspace/${_TARGET_PATH} /workspace/private-repo/${_TARGET_PATH}

  # Step 3: Commit and push changes
  - name: 'gcr.io/cloud-builders/git'
    id: 'commit-and-push'
    dir: '/workspace/private-repo'
    secretEnv: ['ssh_private_key']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        set -x
        # Re-establish SSH for this container
        mkdir -p /root/.ssh
        echo "$ssh_private_key" > /root/.ssh/id_ed25519
        chmod 400 /root/.ssh/id_ed25519
        ssh-keyscan github.com >> /root/.ssh/known_hosts

        git add ${_TARGET_PATH}
        git commit -m "🔄 Update soccer_secret_key from Secret Manager [CI]"
        git push origin ${_BRANCH_NAME}

options:
  logging: CLOUD_LOGGING_ONLY
