substitutions:
  _ENVIRONMENT: 'dev'
  _FOLDER_NAME: 'soccer'

steps:
  # Step 1: Get Firebase project ID
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "📦 Retrieving Firebase project ID..."
        gcloud projects list \
          --filter="name~^${_FOLDER_NAME}-${_ENVIRONMENT}" \
          --format="value(projectId)" \
          | head -n 1 > /workspace/FIREBASE_PROJECT_ID.txt

  # Step 2: Grant required IAM roles to Cloud Build service account
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        firebase_project_id=$(cat /workspace/FIREBASE_PROJECT_ID.txt)
        service_account="cloud-build-sa@org-service-account-001.iam.gserviceaccount.com"

        echo "🔐 Granting roles to $service_account on $firebase_project_id..."

        gcloud projects add-iam-policy-binding "$firebase_project_id" \
          --member="serviceAccount:$service_account" \
          --role="roles/serviceusage.serviceUsageAdmin"

        gcloud projects add-iam-policy-binding "$firebase_project_id" \
          --member="serviceAccount:$service_account" \
          --role="roles/firebase.admin"

        echo "✅ Required IAM roles granted."

  # Step 3: Enable the Cloud Messaging API
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        firebase_project_id=$(cat /workspace/FIREBASE_PROJECT_ID.txt)
        echo "📡 Enabling Firebase Cloud Messaging API for project $firebase_project_id..."
        gcloud services enable cloudmessaging.googleapis.com --project="$firebase_project_id"
        echo "✅ Firebase Cloud Messaging API enabled successfully."

options:
  logging: CLOUD_LOGGING_ONLY
