substitutions:
  _ENVIRONMENT: 'dev'
  _FOLDER_NAME: 'soccer'
  _LOCATION: 'us-central1'  # Valid Firestore location

steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "📦 Fetching Firebase project ID..."
        gcloud projects list \
          --filter="name~^${_FOLDER_NAME}-${_ENVIRONMENT}" \
          --format="value(projectId)" | head -n 1 > /workspace/FIREBASE_PROJECT_ID.txt

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        firebase_project_id=$(cat /workspace/FIREBASE_PROJECT_ID.txt)

        echo "🧱 Creating Firestore database in ${_LOCATION} (Native mode)..."
        gcloud firestore databases create \
          --project="$firebase_project_id" \
          --location="${_LOCATION}" \
          --type=firestore-native

        echo "✅ Firestore database created successfully in ${_LOCATION}."

options:
  logging: CLOUD_LOGGING_ONLY
