substitutions:
  _ENVIRONMENT: 'dev'
  _FOLDER_NAME: 'soccer'

steps:
  # Step 1: Get Firebase project ID
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'get-project-id'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        echo "🔎 Finding project for ${_FOLDER_NAME}-${_ENVIRONMENT}..."
        gcloud projects list \
          --filter="name~^${_FOLDER_NAME}-${_ENVIRONMENT}" \
          --format="value(projectId)" \
          | head -n 1 > /workspace/FIREBASE_PROJECT_ID.txt

        if [ ! -s /workspace/FIREBASE_PROJECT_ID.txt ]; then
          echo "❌ Project ID not found!"
          exit 1
        fi

  # Step 2: Install Firebase CLI
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'install-firebase-cli'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        echo "⬇️ Installing Firebase CLI..."
        curl -sL https://firebase.tools | bash
        mkdir -p /workspace/firebase
        cp /usr/local/bin/firebase /workspace/firebase/
        chmod +x /workspace/firebase/firebase
        echo "✅ Firebase CLI installed."

  # Step 3: Clone source code
  - name: 'gcr.io/cloud-builders/git'
    id: 'pull-files'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -ex
        echo "📦 Cloning from the development branch..."
        git clone -b development --single-branch https://github.com/piotr-gorczynski/Soccer.git /workspace/soccer

        echo "📁 Preparing files for seeding regulations..."
        cp /workspace/soccer/firebase/firebase.json /workspace/firebase/firebase.json
        cp /workspace/soccer/firebase/firestore.rules /workspace/firebase/firestore.rules
        mkdir -p /workspace/firebase/functions/seed-regulations
        cp /workspace/soccer/firebase/functions/seed-regulations/package.json /workspace/firebase/functions/seed-regulations/
        cp /workspace/soccer/firebase/functions/seed-regulations/index.js /workspace/firebase/functions/seed-regulations/
        mkdir -p /workspace/firebase/seed
        cp /workspace/soccer/firebase/seed/tournament_rules.json /workspace/firebase/seed/

  # Step 4: Install dependencies
  - name: 'node:18-slim'
    id: 'install-deps-seed-regulations'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -ex
        cd /workspace/firebase/functions/seed-regulations
        npm install
        echo "📦 Dependencies installed."

  # Step 5: Execute the seeding script
  - name: 'node:18-slim'
    id: 'run-seeding'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        cd /workspace/firebase/functions/seed-regulations
        project_id=$(cat /workspace/FIREBASE_PROJECT_ID.txt)
        export GOOGLE_CLOUD_PROJECT="$project_id"
        node index.js
        echo "✅ Regulations document created."

options:
  logging: CLOUD_LOGGING_ONLY
