substitutions:
  _ENVIRONMENT: 'dev'                         # Environment delivered from the trigger
  _FOLDER_NAME: 'soccer'                      # Parent folder name

steps:
  # Step 1: Update the Cloud SDK and install `jq`
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        apt-get update && apt-get install -y jq
        gcloud components update --quiet

  # Step 2: Retrieve the project ID
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "Checking if project starting with ${_FOLDER_NAME}-${_ENVIRONMENT} exists..."
        gcloud projects list \
          --filter="name~^${_FOLDER_NAME}-${_ENVIRONMENT}" \
          --format="value(projectId)" | head -n 1 > /workspace/project_name.txt

        if [ ! -s /workspace/project_name.txt ] || [ -z "$(cat /workspace/project_name.txt)" ]; then
          echo "Error: Project ID not found. Ensure the project exists."
          exit 1
        fi
        echo "Using project: $(cat /workspace/project_name.txt)"

  # Step 3: Retrieve the secret key and strip newlines
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "Retrieving secret key from Secret Manager..."
        gcloud secrets versions access latest \
          --secret="soccer_secret_key" \
          --project="690882718361" | tr -d '\n' > /workspace/secret_key.txt

        if [ ! -s /workspace/secret_key.txt ] || [ -z "$(cat /workspace/secret_key.txt)" ]; then
          echo "Error: Failed to retrieve secret key. Ensure the secret exists and permissions are configured correctly."
          exit 1
        fi
        echo "Secret key retrieved and stripped of newlines successfully."

  # Step 4: Generate access token and test the service-check endpoint
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "Testing the service-check endpoint for project: $(cat /workspace/project_name.txt)..."
        
        # Debug: Check active credentials
        echo "Current active accounts:"
        gcloud auth list

        # Generate a short-lived access token for the Cloud Function
        gcloud iam service-accounts generate-access-token \
          cloud-build-sa@org-service-account-001.iam.gserviceaccount.com \
          --impersonate-service-account=cloud-build-sa@org-service-account-001.iam.gserviceaccount.com \
          --format="json" | jq -r '.accessToken' > /workspace/access_token.txt

        if [ ! -s /workspace/access_token.txt ] || [ -z "$(cat /workspace/access_token.txt)" ]; then
          echo "Error: Failed to generate access token."
          exit 1
        fi

        # Use the secret key and access token directly in the curl command
        curl -X GET "https://us-central1-$(cat /workspace/project_name.txt).cloudfunctions.net/service-check" \
          -H "Authorization: Bearer $(cat /workspace/access_token.txt)" \
          -H "X-Secret-Key: $(cat /workspace/secret_key.txt)" \
          -H "Cache-Control: no-cache, no-store, must-revalidate" \
          -H "Pragma: no-cache"

options:
  logging: CLOUD_LOGGING_ONLY
