substitutions:
  _ENVIRONMENT: 'dev'
  _FOLDER_NAME: 'soccer'

steps:
  # Step 1: Retrieve the Firebase Project ID
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "🔍 Checking if project starting with ${_FOLDER_NAME}-${_ENVIRONMENT} exists..."
        gcloud projects list \
          --filter="name~^${_FOLDER_NAME}-${_ENVIRONMENT}" \
          --format="value(projectId)" --project="${_ENVIRONMENT}" | head -n 1 > /workspace/soccer_project_id.txt

        if [ ! -s /workspace/soccer_project_id.txt ] || [ -z "$(cat /workspace/soccer_project_id.txt)" ]; then
          echo "❌ Error: Project ID not found. Ensure the project exists."
          exit 1
        fi
        echo "✅ Using project: $(cat /workspace/soccer_project_id.txt)"

  # Step 2: Enable API Keys API (if not already enabled)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        firebase_project_id=$(cat /workspace/soccer_project_id.txt)

        echo "🔄 Checking if API Keys API is enabled in $firebase_project_id..."
        if ! gcloud services list --enabled --project="$firebase_project_id" | grep -q "apikeys.googleapis.com"; then
          echo "⚡ Enabling API Keys API in $firebase_project_id..."
          gcloud services enable apikeys.googleapis.com --project="$firebase_project_id"
          echo "✅ API Keys API enabled in $firebase_project_id!"
        else
          echo "✅ API Keys API is already enabled in $firebase_project_id."
        fi

  # Step 3: Retrieve the Firebase Web API Key programmatically
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        set -x  # Enables command echoing for debugging

        firebase_project_id=$(cat /workspace/soccer_project_id.txt)

        echo "🌐 Retrieving Firebase Web API Key from project $firebase_project_id..."
        firebase_api_key=$(gcloud services api-keys list \
          --format="value(name)" \
          --filter="displayName~firebase" \
          --project="$firebase_project_id" | head -n 1)

        if [ -z "$firebase_api_key" ]; then
          echo "❌ Error: Firebase API Key not found for project $firebase_project_id."
          exit 1
        fi

        echo "$firebase_api_key" > /workspace/firebase_api_key.txt
        echo "✅ Firebase API Key retrieved successfully!"

  # Step 4: Authenticate
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        set -x  # Enables command echoing for debugging

        firebase_project_id=$(cat /workspace/soccer_project_id.txt)

        echo "🔑 Generating OAuth 2 access token for Firebase Admin SDK..."
        gcloud auth print-access-token --impersonate-service-account=firebase-adminsdk-fbsvc@$firebase_project_id.iam.gserviceaccount.com --project="$firebase_project_id" > token.txt
        access_token=$(cat token.txt)

  # Step 5: Create Firebase Test User
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        set -x  # Enables command echoing for debugging

        firebase_api_key=$(cat /workspace/firebase_api_key.txt)

        echo "📩 Creating Firebase Test User..."
        response=$(curl -s -o response.json -w "%{http_code}" -X POST "https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=${firebase_api_key}" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $access_token" \
          -d '{
                "email": "piotr.gorczynski@hotmail.com",
                "password": "bEhBa4V5HzECd!u",
                "returnSecureToken": true
              }')

        if [[ "$response" -ne 200 ]]; then
          echo "❌ Failed to create Firebase user. Response:"
          cat response.json
          exit 1
        fi

        echo "✅ Firebase test user created successfully!"

options:
  logging: CLOUD_LOGGING_ONLY
