# test_delete_unverified_users.yaml
substitutions:
  _ENVIRONMENT: 'dev'
  _FOLDER_NAME: 'soccer'

steps:
  # Step 1: Retrieve the project ID
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'get-project-id'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        echo "Finding project for ${_FOLDER_NAME}-${_ENVIRONMENT}..."
        gcloud projects list \
          --filter="name~^${_FOLDER_NAME}-${_ENVIRONMENT}" \
          --format="value(projectId)" \
          | head -n 1 > /workspace/project_name.txt

        if [ ! -s /workspace/project_name.txt ] || [ -z "$(cat /workspace/project_name.txt)" ]; then
          echo "Error: Project ID not found. Ensure the project exists."
          exit 1
        fi

        echo "Project is: $(cat /workspace/project_name.txt)"

  # Step 2: Run the Cloud Scheduler job that triggers the function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'invoke-scheduled-function'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        project_id=$(cat /workspace/project_name.txt)
        # The default job name for a scheduled function "deleteUnverifiedUsers" is "firebase-schedule-deleteUnverifiedUsers".
        # If your function name or job name is different, change it here.
        scheduler_job_name="firebase-schedule-deleteUnverifiedUsers"

        echo "Listing Cloud Scheduler jobs in $project_id..."
        gcloud scheduler jobs list --project="$project_id"

        echo "Invoking scheduled job: $scheduler_job_name"
        gcloud scheduler jobs run "$scheduler_job_name" --project="$project_id"
        echo "Scheduled function invoked."

  # Step 3: Check logs for errors
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'check-logs'
    entrypoint: bash
    args:
      - '-c'
      - |
        set -e
        project_id=$(cat /workspace/project_name.txt)

        echo "Sleeping for ~30s to let the function run..."
        sleep 30

        echo "Reading logs for function 'deleteUnverifiedUsers' from the last 5 minutes..."
        # Show the last few lines of logs
        gcloud functions logs read deleteUnverifiedUsers \
          --region=us-central1 \
          --project="$project_id" \
          --limit=20 \
          --freshness=5m \
          > /workspace/log_output.txt || true

        echo "===== LOG OUTPUT ====="
        cat /workspace/log_output.txt
        echo "===== END LOG OUTPUT ====="

        # If there's any "ERROR" in the logs, exit non-zero to fail the build
        if grep -q "ERROR" /workspace/log_output.txt; then
          echo "❌ Found error entries in logs for deleteUnverifiedUsers!"
          exit 1
        else
          echo "✅ No error entries found in logs. Test passed."
        fi

options:
  logging: CLOUD_LOGGING_ONLY
