substitutions:
  _ENVIRONMENT: 'dev'                         # Environment delivered from the trigger
  _FOLDER_NAME: 'soccer'                      # Parent folder name

steps:
  # Step 1: Retrieve the project ID
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "Checking if project starting with ${_FOLDER_NAME}-${_ENVIRONMENT} exists..."
        gcloud projects list \
          --filter="name~^${_FOLDER_NAME}-${_ENVIRONMENT}" \
          --format="value(projectId)" | head -n 1 > /workspace/project_name.txt

        if [ ! -s /workspace/project_name.txt ] || [ -z "$(cat /workspace/project_name.txt)" ]; then
          echo "Error: Project ID not found. Ensure the project exists."
          exit 1
        fi
        echo "Using project: $(cat /workspace/project_name.txt)"

  # Step 2: Retrieve the secret key and strip newlines
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "Retrieving secret key from Secret Manager..."
        gcloud secrets versions access latest \
          --secret="soccer_secret_key" \
          --project="690882718361" | tr -d '\n' > /workspace/secret_key.txt

        if [ ! -s /workspace/secret_key.txt ] || [ -z "$(cat /workspace/secret_key.txt)" ]; then
          echo "Error: Failed to retrieve secret key. Ensure the secret exists and permissions are configured correctly."
          exit 1
        fi
        echo "Secret key retrieved successfully: $(cat /workspace/secret_key.txt)"

  # Step 3: Generate identity token and test the service-check endpoint
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "Testing the service-check endpoint for project: $(cat /workspace/project_name.txt)..."

        # Generate an OIDC identity token
        gcloud auth print-identity-token \
          --impersonate-service-account=cloud-build-sa@org-service-account-001.iam.gserviceaccount.com \
          > /workspace/identity_token.txt

        if [ ! -s /workspace/identity_token.txt ] || [ -z "$(cat /workspace/identity_token.txt)" ]; then
          echo "Error: Failed to generate identity token."
          exit 1
        fi

        echo "Generated identity token: $(cat /workspace/identity_token.txt)"

        # Use the secret key and identity token directly in the curl command
        curl --http1.1 -X GET "https://us-central1-$(cat /workspace/project_name.txt).cloudfunctions.net/service-check" \
          -H "Authorization: Bearer $(cat /workspace/identity_token.txt)" \
          -H "X-Secret-Key: $(cat /workspace/secret_key.txt)" \
          -H "Cache-Control: no-cache, no-store, must-revalidate" \
          -H "Pragma: no-cache" \
          -H "Connection: close" \
          -v

options:
  logging: CLOUD_LOGGING_ONLY
